In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline

In [4]:
df =  pd.read_csv('glass.csv')
df

RI     Na    Mg    Al     Si     K    Ca    Ba   Fe  Type
0    1.52101  13.64  4.49  1.10  71.78  0.06  8.75  0.00  0.0     1
1    1.51761  13.89  3.60  1.36  72.73  0.48  7.83  0.00  0.0     1
2    1.51618  13.53  3.55  1.54  72.99  0.39  7.78  0.00  0.0     1
3    1.51766  13.21  3.69  1.29  72.61  0.57  8.22  0.00  0.0     1
4    1.51742  13.27  3.62  1.24  73.08  0.55  8.07  0.00  0.0     1
..       ...    ...   ...   ...    ...   ...   ...   ...  ...   ...
209  1.51623  14.14  0.00  2.88  72.61  0.08  9.18  1.06  0.0     7
210  1.51685  14.92  0.00  1.99  73.06  0.00  8.40  1.59  0.0     7
211  1.52065  14.36  0.00  2.02  73.42  0.00  8.44  1.64  0.0     7
212  1.51651  14.38  0.00  1.94  73.61  0.00  8.48  1.57  0.0     7
213  1.51711  14.23  0.00  2.08  73.36  0.00  8.62  1.67  0.0     7

[214 rows x 10 columns]

# Normalization after splitting data

In [35]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(df.drop(['Type'],axis=1), df['Type'], test_size=0.3, random_state=80)

In [10]:
from sklearn.preprocessing import MinMaxScaler
min_max_scaler = MinMaxScaler()

min_max_scaler1 = MinMaxScaler()
X_train = min_max_scaler1.fit_transform(X_train)
X_train

array([[0.24539069, 0.28976378, 0.79287305, ..., 0.23791822, 0.        ,
        0.        ],
       [0.43283582, 0.41102362, 1.        , ..., 0.30855019, 0.        ,
        0.        ],
       [0.2976295 , 0.34330709, 0.77505568, ..., 0.27881041, 0.        ,
        0.        ],
       ...,
       [0.4547849 , 0.        , 0.38084633, ..., 0.57527881, 0.        ,
        0.        ],
       [0.49692713, 0.60314961, 0.48997773, ..., 0.40241636, 0.        ,
        0.        ],
       [0.44073749, 0.30551181, 0.07349666, ..., 0.54275093, 0.        ,
        0.54901961]])

In [12]:
min_max_scaler2 = MinMaxScaler()
X_test = min_max_scaler2.fit_transform(X_test)
X_test

array([[0.19068736, 0.57244656, 0.89147287, 0.53846154, 0.67766497,
        0.09661836, 0.18057285, 0.        , 0.45945946],
       [0.23004435, 0.48693587, 0.93540052, 0.36630037, 0.75634518,
        0.09500805, 0.22042341, 0.        , 0.        ],
       [0.327051  , 0.75296912, 0.96382429, 0.32600733, 0.58629442,
        0.00966184, 0.24408468, 0.        , 0.        ],
       [0.20288248, 0.59382423, 0.91472868, 0.43589744, 0.76903553,
        0.09017713, 0.14570361, 0.        , 0.        ],
       [0.30543237, 0.52256532, 0.94573643, 0.46520147, 0.68527919,
        0.09339775, 0.20174346, 0.        , 0.32432432],
       [0.18514412, 0.63657957, 0.87596899, 0.36263736, 0.71827411,
        0.08373591, 0.21419676, 0.        , 0.        ],
       [0.47172949, 0.66033254, 0.99741602, 0.21611722, 0.50253807,
        0.03703704, 0.32503113, 0.        , 0.2972973 ],
       [0.44345898, 0.78384798, 0.97157623, 0.10622711, 0.50253807,
        0.01771337, 0.33872976, 0.        , 0.        ],


In [14]:
from sklearn.naive_bayes import GaussianNB
nb4 = GaussianNB()
nb4.fit(X_train, y_train)

GaussianNB(priors=None, var_smoothing=1e-09)

In [16]:
pred4 = nb4.predict(X_test)
pred4

array([2, 2, 7, 2, 2, 2, 2, 7, 2, 2, 5, 2, 2, 7, 1, 2, 5, 1, 5, 2, 5, 2,
       2, 3, 2, 2, 2, 2, 2, 5, 2, 5, 2, 7, 3, 6, 2, 2, 7, 5, 7, 3, 2, 6,
       1, 2, 2, 2, 7, 3, 2, 5, 2, 2, 2, 5, 2, 7, 3, 5, 2, 2, 2, 7, 3],
      dtype=int64)

In [17]:
from sklearn.metrics import confusion_matrix, accuracy_score, precision_score, recall_score, f1_score
confusion_matrix(y_test, pred4)

array([[ 1, 20,  4,  0,  0,  5],
       [ 2, 10,  1,  6,  1,  1],
       [ 0,  5,  1,  2,  0,  1],
       [ 0,  0,  0,  2,  0,  0],
       [ 0,  0,  0,  0,  1,  0],
       [ 0,  0,  0,  0,  0,  2]], dtype=int64)

In [18]:
print('accuracy = {}'.format(accuracy_score(y_test, pred4)))
print('precision = {}'.format(precision_score(y_test, pred4, average='macro')))
print('recall = {}'.format(recall_score(y_test, pred4, average='macro')))
print('F1 score = {}'.format(f1_score(y_test, pred4, average='macro')))      

accuracy = 0.26153846153846155
precision = 0.28465608465608466
recall = 0.6034391534391534
F1 score = 0.3191197691197691


# Standardization after splitting data

In [28]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(df.drop(['Type'],axis=1), df['Type'], test_size=0.3, random_state=80)


In [29]:
from sklearn.preprocessing import StandardScaler
sc1 = StandardScaler()

X_train = sc1.fit_transform(X_train)
X_train

array([[-0.51700525, -0.71583756,  0.68117471, ..., -0.66692409,
        -0.39542711, -0.54868246],
       [ 0.86101842,  0.20663849,  1.29164154, ..., -0.14790489,
        -0.39542711, -0.54868246],
       [-0.13296587, -0.30851047,  0.62866144, ..., -0.36643929,
        -0.39542711, -0.54868246],
       ...,
       [ 1.02237951, -2.92019591, -0.53319477, ...,  1.81207551,
        -0.39542711, -0.54868246],
       [ 1.33219279,  1.66822392, -0.21155096, ...,  0.54184431,
        -0.39542711, -0.54868246],
       [ 0.91910841, -0.59603547, -1.43904877, ...,  1.57305351,
        -0.39542711,  2.39360961]])

In [30]:
sc2 = StandardScaler()

X_test = sc2.fit_transform(X_test)
X_test

array([[-6.17499967e-01, -1.74975315e-01,  3.45281356e-01,
         1.00965930e+00, -9.33714061e-02,  8.09823547e-02,
        -4.22982223e-01, -2.51276263e-01,  1.01098794e+00],
       [-3.69672995e-01, -6.55541323e-01,  4.94435342e-01,
        -1.42566759e-01,  3.65514894e-01,  6.75883266e-02,
        -1.79066774e-01, -2.51276263e-01, -6.73991958e-01],
       [ 2.41168132e-01,  8.39552922e-01,  5.90946746e-01,
        -4.12236686e-01, -6.26271626e-01, -6.42295164e-01,
        -3.42419765e-02, -2.51276263e-01, -6.73991958e-01],
       [-5.40708511e-01, -5.48338136e-02,  4.24245231e-01,
         3.23226752e-01,  4.39528814e-01,  2.74062422e-02,
        -6.36408241e-01, -2.51276263e-01, -6.73991958e-01],
       [ 1.05037824e-01, -4.55305486e-01,  5.29530398e-01,
         5.19350336e-01, -4.89630544e-02,  5.41942984e-02,
        -2.93402141e-01, -2.51276263e-01,  5.15405615e-01],
       [-6.52405175e-01,  1.85449190e-01,  2.92638772e-01,
        -1.67082207e-01,  1.43473136e-01, -2.616987

In [31]:
from sklearn.naive_bayes import GaussianNB
nb5 = GaussianNB()
nb5.fit(X_train, y_train)

GaussianNB(priors=None, var_smoothing=1e-09)

In [32]:
pred5 = nb5.predict(X_test)
pred5

array([2, 2, 7, 2, 2, 2, 2, 2, 2, 2, 5, 2, 2, 7, 2, 2, 5, 2, 5, 2, 5, 2,
       2, 2, 2, 2, 2, 2, 2, 5, 2, 7, 2, 5, 2, 5, 2, 2, 7, 5, 7, 2, 5, 7,
       2, 2, 2, 2, 7, 2, 2, 5, 2, 7, 7, 5, 2, 7, 2, 5, 2, 5, 2, 7, 2],
      dtype=int64)

In [33]:
from sklearn.metrics import confusion_matrix, accuracy_score, precision_score, recall_score, f1_score
confusion_matrix(y_test, pred5)

array([[ 0, 24,  0,  1,  0,  5],
       [ 0, 10,  0,  8,  0,  3],
       [ 0,  7,  0,  2,  0,  0],
       [ 0,  0,  0,  2,  0,  0],
       [ 0,  0,  0,  0,  0,  1],
       [ 0,  0,  0,  0,  0,  2]], dtype=int64)

In [34]:
print('accuracy = {}'.format(accuracy_score(y_test, pred5)))
print('precision = {}'.format(precision_score(y_test, pred5, average='macro')))
print('recall = {}'.format(recall_score(y_test, pred5, average='macro')))
print('F1 score = {}'.format(f1_score(y_test, pred5, average='macro')))      

accuracy = 0.2153846153846154
precision = 0.09659446244812098
recall = 0.41269841269841273
F1 score = 0.1494899365867108


C:\Users\Lenovo\Anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1272: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
