In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline

In [2]:
df =  pd.read_csv('glass.csv')

In [61]:
df

RI     Na    Mg    Al     Si     K    Ca    Ba   Fe  Type
0    1.52101  13.64  4.49  1.10  71.78  0.06  8.75  0.00  0.0     1
1    1.51761  13.89  3.60  1.36  72.73  0.48  7.83  0.00  0.0     1
2    1.51618  13.53  3.55  1.54  72.99  0.39  7.78  0.00  0.0     1
3    1.51766  13.21  3.69  1.29  72.61  0.57  8.22  0.00  0.0     1
4    1.51742  13.27  3.62  1.24  73.08  0.55  8.07  0.00  0.0     1
..       ...    ...   ...   ...    ...   ...   ...   ...  ...   ...
209  1.51623  14.14  0.00  2.88  72.61  0.08  9.18  1.06  0.0     7
210  1.51685  14.92  0.00  1.99  73.06  0.00  8.40  1.59  0.0     7
211  1.52065  14.36  0.00  2.02  73.42  0.00  8.44  1.64  0.0     7
212  1.51651  14.38  0.00  1.94  73.61  0.00  8.48  1.57  0.0     7
213  1.51711  14.23  0.00  2.08  73.36  0.00  8.62  1.67  0.0     7

[214 rows x 10 columns]

# Default

In [62]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(df.drop(['Type'],axis=1), df['Type'], test_size=0.3, random_state=80)

In [63]:
X_train.shape

(149, 9)

In [64]:
X_test.shape

(65, 9)

In [65]:
from sklearn.naive_bayes import GaussianNB
nb = GaussianNB()
nb.fit(X_train, y_train)

GaussianNB(priors=None, var_smoothing=1e-09)

In [66]:
pred = nb.predict(X_test)
pred

array([1, 3, 3, 3, 1, 3, 1, 3, 3, 3, 5, 1, 1, 7, 1, 3, 2, 1, 1, 3, 5, 3,
       1, 3, 3, 3, 3, 1, 1, 5, 3, 2, 3, 3, 3, 6, 3, 3, 3, 2, 7, 3, 2, 6,
       1, 3, 1, 3, 7, 2, 3, 2, 3, 3, 3, 5, 3, 7, 3, 5, 1, 2, 3, 7, 3],
      dtype=int64)

In [67]:
from sklearn.metrics import confusion_matrix, accuracy_score, precision_score, recall_score, f1_score
confusion_matrix(y_test, pred)

array([[ 5,  0, 23,  0,  0,  2],
       [ 7,  6,  3,  3,  1,  1],
       [ 2,  0,  6,  1,  0,  0],
       [ 0,  1,  0,  1,  0,  0],
       [ 0,  0,  0,  0,  1,  0],
       [ 0,  0,  0,  0,  0,  2]], dtype=int64)

In [68]:
print('accuracy = {}'.format(accuracy_score(y_test, pred)))
print('precision = {}'.format(precision_score(y_test, pred, average='macro')))
print('recall = {}'.format(recall_score(y_test, pred, average='macro')))
print('F1 score = {}'.format(f1_score(y_test, pred, average='macro')))      

accuracy = 0.3230769230769231
precision = 0.4169642857142857
recall = 0.6031746031746031
F1 score = 0.41205610108049134


# Normalization before splitting data

In [19]:
from sklearn.preprocessing import MinMaxScaler
min_max_scaler = MinMaxScaler()
df_minmax = min_max_scaler.fit_transform(df.drop(['Type'], axis=1))
df_minmax

array([[0.43283582, 0.43759398, 1.        , ..., 0.30855019, 0.        ,
        0.        ],
       [0.28358209, 0.47518797, 0.80178174, ..., 0.22304833, 0.        ,
        0.        ],
       [0.22080773, 0.42105263, 0.79064588, ..., 0.21840149, 0.        ,
        0.        ],
       ...,
       [0.41703248, 0.54586466, 0.        , ..., 0.27973978, 0.52063492,
        0.        ],
       [0.23529412, 0.54887218, 0.        , ..., 0.28345725, 0.4984127 ,
        0.        ],
       [0.26163301, 0.52631579, 0.        , ..., 0.2964684 , 0.53015873,
        0.        ]])

In [21]:
norm_df = pd.DataFrame(df_minmax, columns = df.columns[:-1])
norm_df

RI        Na        Mg        Al        Si         K        Ca  \
0    0.432836  0.437594  1.000000  0.252336  0.351786  0.009662  0.308550   
1    0.283582  0.475188  0.801782  0.333333  0.521429  0.077295  0.223048   
2    0.220808  0.421053  0.790646  0.389408  0.567857  0.062802  0.218401   
3    0.285777  0.372932  0.821826  0.311526  0.500000  0.091787  0.259294   
4    0.275241  0.381955  0.806236  0.295950  0.583929  0.088567  0.245353   
..        ...       ...       ...       ...       ...       ...       ...   
209  0.223003  0.512782  0.000000  0.806854  0.500000  0.012882  0.348513   
210  0.250219  0.630075  0.000000  0.529595  0.580357  0.000000  0.276022   
211  0.417032  0.545865  0.000000  0.538941  0.644643  0.000000  0.279740   
212  0.235294  0.548872  0.000000  0.514019  0.678571  0.000000  0.283457   
213  0.261633  0.526316  0.000000  0.557632  0.633929  0.000000  0.296468   

           Ba   Fe  
0    0.000000  0.0  
1    0.000000  0.0  
2    0.000000  0.0  
3    0.000000  0.0  
4    0.000000  0.0  
..        ...  ...  
209  0.336508  0.0  
210  0.504762  0.0  
211  0.520635  0.0  
212  0.498413  0.0  
213  0.530159  0.0  

[214 rows x 9 columns]

In [22]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(norm_df, df['Type'], test_size=0.3, random_state=80)

In [24]:
X_train.shape

(149, 9)

In [26]:
from sklearn.naive_bayes import GaussianNB
nb2 = GaussianNB()
nb2.fit(X_train, y_train)

GaussianNB(priors=None, var_smoothing=1e-09)

In [27]:
pred2 = nb2.predict(X_test)
pred2

array([1, 3, 3, 3, 1, 3, 1, 3, 3, 3, 5, 1, 1, 7, 1, 3, 2, 1, 1, 3, 5, 3,
       1, 3, 3, 3, 3, 1, 1, 5, 3, 2, 3, 3, 3, 6, 3, 3, 3, 2, 7, 3, 2, 6,
       1, 3, 1, 3, 7, 2, 3, 2, 3, 3, 3, 5, 3, 7, 3, 5, 1, 2, 3, 7, 3],
      dtype=int64)

In [28]:
from sklearn.metrics import confusion_matrix, accuracy_score, precision_score, recall_score, f1_score
confusion_matrix(y_test, pred2)

array([[ 5,  0, 23,  0,  0,  2],
       [ 7,  6,  3,  3,  1,  1],
       [ 2,  0,  6,  1,  0,  0],
       [ 0,  1,  0,  1,  0,  0],
       [ 0,  0,  0,  0,  1,  0],
       [ 0,  0,  0,  0,  0,  2]], dtype=int64)

In [29]:
print('accuracy = {}'.format(accuracy_score(y_test, pred2)))
print('precision = {}'.format(precision_score(y_test, pred2, average='macro')))
print('recall = {}'.format(recall_score(y_test, pred2, average='macro')))
print('F1 score = {}'.format(f1_score(y_test, pred2, average='macro')))      

accuracy = 0.3230769230769231
precision = 0.4169642857142857
recall = 0.6031746031746031
F1 score = 0.41205610108049134


# Standardization before splitting data

In [32]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()

df_scale = sc.fit_transform(df.drop(['Type'], axis=1))
df_scale

array([[ 0.87286765,  0.28495326,  1.25463857, ..., -0.14576634,
        -0.35287683, -0.5864509 ],
       [-0.24933347,  0.59181718,  0.63616803, ..., -0.79373376,
        -0.35287683, -0.5864509 ],
       [-0.72131806,  0.14993314,  0.60142249, ..., -0.82894938,
        -0.35287683, -0.5864509 ],
       ...,
       [ 0.75404635,  1.16872135, -1.86551055, ..., -0.36410319,
         2.95320036, -0.5864509 ],
       [-0.61239854,  1.19327046, -1.86551055, ..., -0.33593069,
         2.81208731, -0.5864509 ],
       [-0.41436305,  1.00915211, -1.86551055, ..., -0.23732695,
         3.01367739, -0.5864509 ]])

In [33]:
sc_df = pd.DataFrame(df_scale, columns = df.columns[:-1])
sc_df

RI        Na        Mg        Al        Si         K        Ca  \
0    0.872868  0.284953  1.254639 -0.692442 -1.127082 -0.671705 -0.145766   
1   -0.249333  0.591817  0.636168 -0.170460  0.102319 -0.026213 -0.793734   
2   -0.721318  0.149933  0.601422  0.190912  0.438787 -0.164533 -0.828949   
3   -0.232831 -0.242853  0.698710 -0.310994 -0.052974  0.112107 -0.519052   
4   -0.312045 -0.169205  0.650066 -0.411375  0.555256  0.081369 -0.624699   
..        ...       ...       ...       ...       ...       ...       ...   
209 -0.704815  0.898681 -1.865511  2.881125 -0.052974 -0.640968  0.157088   
210 -0.500178  1.856097 -1.865511  1.094342  0.529374 -0.763919 -0.392276   
211  0.754046  1.168721 -1.865511  1.154570  0.995252 -0.763919 -0.364103   
212 -0.612399  1.193270 -1.865511  0.993960  1.241133 -0.763919 -0.335931   
213 -0.414363  1.009152 -1.865511  1.275028  0.917606 -0.763919 -0.237327   

           Ba        Fe  
0   -0.352877 -0.586451  
1   -0.352877 -0.586451  
2   -0.352877 -0.586451  
3   -0.352877 -0.586451  
4   -0.352877 -0.586451  
..        ...       ...  
209  1.783978 -0.586451  
210  2.852405 -0.586451  
211  2.953200 -0.586451  
212  2.812087 -0.586451  
213  3.013677 -0.586451  

[214 rows x 9 columns]

In [34]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(sc_df, df['Type'], test_size=0.3, random_state=80)

In [35]:
from sklearn.naive_bayes import GaussianNB
nb3 = GaussianNB()
nb3.fit(X_train, y_train)

GaussianNB(priors=None, var_smoothing=1e-09)

In [37]:
pred3 = nb3.predict(X_test)
pred3

array([1, 3, 3, 3, 3, 3, 1, 3, 3, 3, 5, 1, 1, 7, 1, 3, 2, 1, 1, 3, 5, 3,
       1, 3, 3, 3, 3, 1, 1, 5, 3, 2, 3, 3, 3, 6, 3, 3, 3, 2, 7, 3, 2, 6,
       1, 3, 1, 3, 7, 2, 3, 2, 3, 3, 3, 5, 3, 7, 3, 5, 1, 2, 3, 7, 3],
      dtype=int64)

RI        Na        Mg        Al        Si         K        Ca  \
139 -0.536485 -0.660188  0.608372  0.391674  0.632903  0.235057 -0.681044   
0    0.872868  0.284953  1.254639 -0.692442 -1.127082 -0.671705 -0.145766   
26  -0.143715 -0.242853  0.552779 -0.070079 -0.014151  0.142844 -0.371146   
107  5.137232 -1.359837 -1.865511 -0.893204 -3.223534 -0.579492  5.094318   
182  0.262258  0.910956 -1.865511  1.295104  0.115260 -0.763919  1.354419   
..        ...       ...       ...       ...       ...       ...       ...   
50   1.595697  0.383150  0.719557 -1.876939 -1.165905 -0.625599  0.776883   
10  -0.876446 -0.844306  0.538881  0.231064  0.710549  0.265795 -0.610613   
166  1.037897 -2.918706 -0.677213  0.231064  1.021135  0.127475  1.875610   
188  1.354754  1.782449 -0.336707  1.234875 -3.094124  0.404115  0.565589   
175  0.932278 -0.537442 -1.636190  0.130683  0.956429 -0.564123  1.629101   

           Ba        Fe  
139 -0.352877 -0.586451  
0   -0.352877 -0.586451  
26  -0.352877 -0.586451  
107 -0.352877  1.882411  
182 -0.352877 -0.586451  
..        ...       ...  
50  -0.352877  1.059457  
10  -0.352877  1.882411  
166 -0.352877 -0.586451  
188 -0.352877 -0.586451  
175 -0.352877  2.293888  

[149 rows x 9 columns]

In [39]:
from sklearn.metrics import confusion_matrix, accuracy_score, precision_score, recall_score, f1_score
confusion_matrix(y_test, pred3)

array([[ 5,  0, 23,  0,  0,  2],
       [ 6,  6,  4,  3,  1,  1],
       [ 2,  0,  6,  1,  0,  0],
       [ 0,  1,  0,  1,  0,  0],
       [ 0,  0,  0,  0,  1,  0],
       [ 0,  0,  0,  0,  0,  2]], dtype=int64)

In [40]:
print('accuracy = {}'.format(accuracy_score(y_test, pred3)))
print('precision = {}'.format(precision_score(y_test, pred3, average='macro')))
print('recall = {}'.format(recall_score(y_test, pred3, average='macro')))
print('F1 score = {}'.format(f1_score(y_test, pred3, average='macro')))      

accuracy = 0.3230769230769231
precision = 0.42059607059607057
recall = 0.6031746031746031
F1 score = 0.4117755629383537
