In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline

In [2]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import confusion_matrix, accuracy_score, f1_score, precision_score, recall_score
from sklearn.preprocessing import StandardScaler

In [3]:
df = pd.read_csv('clean_data.csv')
df

age    bp     sg   al   su         bgr    bu   sc         sod       pot  \
0    48.0  80.0  1.020  1.0  0.0  121.000000  36.0  1.2  137.528754  4.627244   
1     7.0  50.0  1.020  4.0  0.0  148.036517  18.0  0.8  137.528754  4.627244   
2    62.0  80.0  1.010  2.0  3.0  423.000000  53.0  1.8  137.528754  4.627244   
3    48.0  70.0  1.005  4.0  0.0  117.000000  56.0  3.8  111.000000  2.500000   
4    51.0  80.0  1.010  2.0  0.0  106.000000  26.0  1.4  137.528754  4.627244   
..    ...   ...    ...  ...  ...         ...   ...  ...         ...       ...   
388  55.0  80.0  1.020  0.0  0.0  140.000000  49.0  0.5  150.000000  4.900000   
389  42.0  70.0  1.025  0.0  0.0   75.000000  31.0  1.2  141.000000  3.500000   
390  12.0  80.0  1.020  0.0  0.0  100.000000  26.0  0.6  137.000000  4.400000   
391  17.0  60.0  1.025  0.0  0.0  114.000000  50.0  1.0  135.000000  4.900000   
392  58.0  80.0  1.025  0.0  0.0  131.000000  18.0  1.1  141.000000  3.500000   

     hemo  pcc_present  ba_present  htn_  dm_  cad_  poor_appet  anemia_  \
0    15.4            0           0     1    1     0           0        0   
1    11.3            0           0     0    0     0           0        0   
2     9.6            0           0     0    1     0           1        1   
3    11.2            1           0     1    0     0           1        1   
4    11.6            0           0     0    0     0           0        0   
..    ...          ...         ...   ...  ...   ...         ...      ...   
388  15.7            0           0     0    0     0           0        0   
389  16.5            0           0     0    0     0           0        0   
390  15.8            0           0     0    0     0           0        0   
391  14.2            0           0     0    0     0           0        0   
392  15.8            0           0     0    0     0           0        0   

     pedal_edema  ckd_  
0              0     1  
1              0     1  
2              0     1  
3              1     1  
4              0     1  
..           ...   ...  
388            0     0  
389            0     0  
390            0     0  
391            0     0  
392            0     0  

[393 rows x 20 columns]

In [4]:
#17 ทำ Standardize ข้อมูล features ทั้งหมดก่อนเทรนโมเดล 
X = df.drop('ckd_', axis=1)
y = df['ckd_']

sc_X = StandardScaler()
sc_y = StandardScaler()

X = sc_X.fit_transform(X)
#y = sc_y.fit_transform(y)

In [5]:
# split data
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=100)

In [23]:
X

array([[-0.20710585,  0.24877598,  0.49560476, ..., -0.51348378,
        -0.42447636, -0.48964031],
       [-2.61943511, -1.97519987,  0.49560476, ..., -0.51348378,
        -0.42447636, -0.48964031],
       [ 0.61661633,  0.24877598, -1.36499527, ...,  1.94748117,
         2.3558438 , -0.48964031],
       ...,
       [-2.32524862,  0.24877598,  0.49560476, ..., -0.51348378,
        -0.42447636, -0.48964031],
       [-2.03106212, -1.23387459,  1.42590477, ..., -0.51348378,
        -0.42447636, -0.48964031],
       [ 0.38126714,  0.24877598,  1.42590477, ..., -0.51348378,
        -0.42447636, -0.48964031]])

In [6]:
y_train

339    0
329    0
337    0
373    0
305    0
      ..
343    0
359    0
323    0
280    0
8      1
Name: ckd_, Length: 314, dtype: int64

In [7]:
y_test

124    1
140    1
295    0
252    0
327    0
      ..
233    1
209    1
187    1
27     1
235    1
Name: ckd_, Length: 79, dtype: int64

In [8]:
# train data
logistic_regression = LogisticRegression()
logistic_regression.fit(X_train, y_train)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='auto', n_jobs=None, penalty='l2',
                   random_state=None, solver='lbfgs', tol=0.0001, verbose=0,
                   warm_start=False)

In [9]:
predicted = logistic_regression.predict(X_test)
predicted

array([1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1,
       1, 0, 1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 0, 1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 1, 0,
       1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1], dtype=int64)

In [12]:
#18 วัดผลโมเดล โดยใช้ confusion matrix และ ประเมินผลด้วยคะแนน Accuracy, F1 score, Recall, Precision แล้วดูว่าแบบไม่ standardize กับ แบบ standardize แบบใดให้ผลลัพธ์ดีกว่า

print(confusion_matrix(y_test,predicted))

[[25  0]
 [ 0 54]]


In [13]:
print('Accuracy = ', accuracy_score(y_test,predicted))
print('F1-Score = ', f1_score(y_test,predicted))
print('Precision = ', precision_score(y_test,predicted))
print('Recall = ', recall_score(y_test,predicted))

Accuracy =  1.0
F1-Score =  1.0
Precision =  1.0
Recall =  1.0


In [14]:
#18 --> สรุปว่า แบบstandardize ให้ผลลัพธ์ดีกว่า แบบไม่ standardize

In [16]:
#19 เลือก features ที่สนใจ และทำ standardization, เทรนโมเดล, วัดผล 
X2 = df[['sg','al','hemo','htn_','dm_']]
y = df['ckd_']

sc_X = StandardScaler()
X2 = sc_X.fit_transform(X2)

In [17]:
X2

array([[ 0.49560476, -0.02750753,  1.0731918 ,  1.29362645,  1.36697225],
       [ 0.49560476,  2.32606104, -0.43659241, -0.77302068, -0.73154374],
       [-1.36499527,  0.75701533, -1.0626005 , -0.77302068,  1.36697225],
       ...,
       [ 0.49560476, -0.81203039,  1.22048782, -0.77302068, -0.73154374],
       [ 1.42590477, -0.81203039,  0.63130374, -0.77302068, -0.73154374],
       [ 1.42590477, -0.81203039,  1.22048782, -0.77302068, -0.73154374]])

In [18]:
X2_train, X2_test, y_train, y_test = train_test_split(X2, y, test_size=0.2, random_state=100)

In [19]:
logistic_regression = LogisticRegression()
logistic_regression.fit(X2_train,y_train)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='auto', n_jobs=None, penalty='l2',
                   random_state=None, solver='lbfgs', tol=0.0001, verbose=0,
                   warm_start=False)

In [20]:
predicted2 = logistic_regression.predict(X2_test)
predicted2

array([1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1,
       1, 0, 1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 0, 1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 1, 0,
       1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1], dtype=int64)

In [21]:
print(confusion_matrix(y_test,predicted2))

[[25  0]
 [ 0 54]]


In [22]:
print('Accuracy = ', accuracy_score(y_test,predicted2))
print('F1-Score = ', f1_score(y_test,predicted2))
print('Precision = ', precision_score(y_test,predicted2))
print('Recall = ', recall_score(y_test,predicted2))

Accuracy =  1.0
F1-Score =  1.0
Precision =  1.0
Recall =  1.0
